#!/usr/bin/python

import sys
import os

def convert(directory, executable):
    files = [f for f in os.listdir(directory)]
    if not os.path.exists(directory + "/point_clouds_with_branches"):
        os.makedirs(directory + "/point_clouds_with_branches")
    for f in files:
        path_to_obj = os.path.abspath(directory + "/" + f);
        if path_to_obj.endswith('obj'):
            input_clo = " --input_path " + path_to_obj
            output_path = directory + "/point_clouds_with_branches/" + f + ".obj";
            print "writing new obj to " + output_path
            output_clo = " --output_path " + output_path
            os.system(executable + input_clo + output_clo + " --recalculate_branches true --output_as_json false")

if __name__ == '__main__':
    if (len(sys.argv) < 3):
        print "please give path to directory that contains the obj files for which you want branches generated"
    else:
        directory = os.path.abspath(os.path.expanduser(sys.argv[1]))
        executable = os.path.abspath(os.path.expanduser(sys.argv[2]))
        convert(directory, executable)
