#!/usr/bin/python

import sys
import os
import json

def convert(directory, executable, path):
    files = [f for f in os.listdir(directory)]
    if (not os.path.exists(directory + "/json") and not path):
        os.makedirs(directory + "/json")
    if (not os.path.exists(directory + "/path_json") and path):
        os.makedirs(directory + "/path_json")
    for f in files:
        path_to_obj = os.path.abspath(directory + "/" + f);
        if path_to_obj.endswith('obj'):

            print "Evaluating: " + path_to_obj

            input_clo = " --input_path " + path_to_obj
            if (path):
                output_path = directory + "/path_json/" + f + ".csv";
            else:
                output_path = directory + "/json/" + f + ".json";
            output_clo = " --output_path " + output_path
            if (path):
                os.system(executable + input_clo + output_clo + " --path --recalculate_branches false --output_as_json true")
            else:
                os.system(executable + input_clo + output_clo + " --recalculate_branches false --output_as_json true")

if __name__ == '__main__':
    if (len(sys.argv) < 3):
        print "please give path to directory that contains the obj files you want to convert to JSON and the path to the converter executable. Optionally also provide flag --path to generate paths instead of graphs jsons"
    else:

        directory = os.path.abspath(os.path.expanduser(sys.argv[1]))
        executable = os.path.abspath(os.path.expanduser(sys.argv[2]))
        path = 0
        if (len(sys.argv) > 3):
            path = 1
        convert(directory, executable, path)
